import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync, rmSync, existsSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const pagesDir = join(root, "src", "pages");
const outDir = resolve(root, "..", "Assets", "Html");
const stageDir = join(root, ".vite-out");
const viteBin = join(root, "node_modules", "vite", "bin", "vite.js");

const EXTERNAL_REFS_ALLOWED = new Set(["dota2_performance"]);

const LICENSE = `<!--
 * Copyright (C) 2026 Ardysa
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 -->
`;

const banner = (page) => `<!-- GENERATED by Frontend/build.mjs from Frontend/src/pages/${page}/ — do not edit this file. -->\n`;

function assertHostContract(page, html) {
   const fail = (why) => {
      throw new Error(`${page}.html: ${why}`);
   };
   if (!html.includes('<html lang="en"')) fail('missing the `<html lang="en"` splice anchor (WebViewTheming.Apply)');
   if (!html.includes("</head>")) fail("missing the `</head>` splice anchor (WebViewTheming.Apply)");

   if (EXTERNAL_REFS_ALLOWED.has(page)) {
      const scripts = [...html.matchAll(/<script[^>]+\ssrc\s*=\s*["']([^"']+)["']/gi)].map((m) => m[1]);
      const stylesheets = [...html.matchAll(/<link[^>]+rel\s*=\s*["']stylesheet["'][^>]*\shref\s*=\s*["']([^"']+)["']/gi)].map((m) => m[1]);
      for (const src of scripts)
         if (src !== "vendor/tailwind.min.js") fail(`unexpected external <script src="${src}"> — only vendor/tailwind.min.js is allowed here`);
      for (const href of stylesheets)
         if (href !== "fonts.css") fail(`unexpected external stylesheet <link href="${href}"> — only fonts.css is allowed here`);
      return;
   }

   if (/<script[^>]+\ssrc=/i.test(html)) fail("has an external <script src> — unreachable under NavigateToString");
   if (/<link[^>]+rel=["']stylesheet["']/i.test(html)) fail("has an external stylesheet <link> — unreachable under NavigateToString");
}

const requested = process.argv.slice(2);
const pages = requested.length
   ? requested
   : readdirSync(pagesDir, { withFileTypes: true })
        .filter((d) => d.isDirectory() && existsSync(join(pagesDir, d.name, "index.html")))
        .map((d) => d.name);

if (!pages.length) {
   console.error("no pages found under src/pages/");
   process.exit(1);
}

rmSync(stageDir, { recursive: true, force: true });

for (const page of pages) {
   if (!existsSync(join(pagesDir, page, "index.html"))) {
      console.error(`unknown page "${page}" (no src/pages/${page}/index.html)`);
      process.exit(1);
   }

   execFileSync(process.execPath, [viteBin, "build"], {
      cwd: root,
      stdio: ["ignore", "ignore", "inherit"],
      env: { ...process.env, AMT_PAGE: page },
   });

   const staged = join(stageDir, "src", "pages", page, "index.html");
   if (!existsSync(staged)) throw new Error(`${page}: vite produced no output at ${staged}`);

   let html = readFileSync(staged, "utf8");

   html = html.replace(/\s+crossorigin(?=[\s>])/gi, "");

   const out = LICENSE + banner(page) + html.replace(/^\s*<!doctype/i, "<!doctype");
   assertHostContract(page, out);

   const target = join(outDir, `${page}.html`);
   writeFileSync(target, out);
   const kb = (statSync(target).size / 1024).toFixed(0);
   console.log(`  ${page}.html  ${kb} KB`);
}

rmSync(stageDir, { recursive: true, force: true });
console.log(`\n${pages.length} page(s) -> Assets/Html/`);
