import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const htmlDir = join(root, "..", "Assets", "Html");
const pagesDir = join(root, "src", "pages");
const debtFile = join(root, "theme-debt.json");

const strip = (css) => css.replace(/\/\*[\s\S]*?\*\//g, "");

function themeRules() {
   const rules = [];
   for (const m of strip(readFileSync(join(htmlDir, "theme.css"), "utf8")).matchAll(/([^{}]+)\{([^}]*)\}/g)) {
      const selector = m[1].replace(/\s+/g, " ").trim();
      if (!selector.includes("data-theme")) continue;
      const targets = [
         ...new Set((selector.match(/(?:^|[\s>+~])([.#][A-Za-z][\w-]*)/g) ?? []).map((s) => s.trim())),
      ];
      if (!targets.length) continue;
      const decls = m[2]
         .split(";")
         .map((d) => d.replace(/\s+/g, " ").trim())
         .filter(Boolean);
      rules.push({ selector, targets, decls });
   }
   return rules;
}

function usedNames(html) {
   const names = new Set();
   const addClasses = (value) => value.split(/\s+/).filter(Boolean).forEach((c) => names.add("." + c));
   for (const m of html.matchAll(/\bclass(?:Name)?\s*=\s*"([^"]*)"/g)) addClasses(m[1]);
   for (const m of html.matchAll(/\bid\s*=\s*"([^"]+)"/g)) names.add("#" + m[1]);
   for (const m of html.matchAll(/class(?:List)?\s*(?:\.\s*(?:add|remove|toggle)\s*\(|=)\s*"([^"]*)"/g))
      addClasses(m[1]);
   for (const m of html.matchAll(/getElementById\(\s*"([^"]+)"/g)) names.add("#" + m[1]);
   return names;
}

const isGenerated = (html) => html.includes("GENERATED by Frontend/build.mjs");

const allPages = readdirSync(htmlDir)
   .filter((f) => f.endsWith(".html"))
   .map((f) => f.replace(/\.html$/, ""));

const ported = new Set(
   existsSync(pagesDir)
      ? readdirSync(pagesDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)
      : [],
);

function originalHtml(page) {
   const path = join(htmlDir, `${page}.html`);
   if (existsSync(path)) {
      const text = readFileSync(path, "utf8");
      if (!isGenerated(text)) return text;
   }
   try {
      return execFileSync("git", ["show", `HEAD:Assets/Html/${page}.html`], {
         cwd: join(root, ".."),
         encoding: "utf8",
         maxBuffer: 64 * 1024 * 1024,
      });
   } catch {
      return null;
   }
}

const rules = themeRules();

function deriveDebt(page) {
   const html = originalHtml(page);
   if (html === null) return null;
   const names = usedNames(html);
   return rules
      .filter((r) => r.targets.some((t) => names.has(t)))
      .map((r) => ({ targets: r.targets.filter((t) => names.has(t)), decls: r.decls }));
}

if (process.argv[2] === "--freeze") {
   const prevStore = existsSync(debtFile) ? JSON.parse(readFileSync(debtFile, "utf8")) : {};
   const frozen = prevStore.debt ?? prevStore;
   let changed = 0;
   for (const page of allPages) {
      const debt = deriveDebt(page);
      if (debt === null) continue;
      frozen[page] = debt;
      changed++;
   }
   writeFileSync(debtFile, JSON.stringify({ debt: frozen, accepted: prevStore.accepted ?? {} }, null, 3) + "\n");
   console.log(`froze theme.css debt for ${changed} page(s) -> theme-debt.json`);
   process.exit(0);
}

const store = existsSync(debtFile) ? JSON.parse(readFileSync(debtFile, "utf8")) : {};
const frozen = store.debt ?? store;
const accepted = store.accepted ?? {};

function builtCss(page) {
   const path = join(htmlDir, `${page}.html`);
   if (!existsSync(path)) return "";
   return [...readFileSync(path, "utf8").matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)]
      .map((m) => m[1])
      .join("\n");
}

function lightDeclsInBuild(page) {
   if (!existsSync(join(htmlDir, `${page}.html`))) return null;
   const css = builtCss(page);
   const decls = new Set();
   for (const m of strip(css).matchAll(/([^{}]*\[data-theme=["']?light["']?\][^{}]*)\{([^}]*)\}/g))
      for (const d of m[2].split(";").map((s) => s.replace(/\s+/g, " ").trim()).filter(Boolean))
         decls.add(normalize(d));
   return decls;
}

function normalize(decl) {
   return decl
      .toLowerCase()
      .replace(/\s*:\s*/, ":")
      .replace(/#([0-9a-f])\1([0-9a-f])\2([0-9a-f])\3\b/g, "#$1$2$3")
      .replace(/\s+/g, " ")
      .trim();
}

function lightTokens() {
   const css = strip(readFileSync(join(htmlDir, "theme.css"), "utf8"));
   const map = new Map();
   for (const m of css.matchAll(/(:root|html)(?:\[[^\]]*light[^\]]*\])[^{]*\{([^}]*)\}/g))
      for (const d of m[2].split(";")) {
         const kv = d.match(/(--[\w-]+)\s*:\s*(.+)/);
         if (kv) map.set(kv[1], normalize(`x:${kv[2]}`).slice(2));
      }
   return map;
}

const INERT = new Set(["none", "0", "transparent", "initial", "unset"]);

function isPaid(decl, present, pageCss, tokens) {
   const norm = normalize(decl);
   if (present.has(norm)) return "verbatim";

   const [prop, ...rest] = norm.split(":");
   const wanted = rest.join(":").trim();

   const asVar = wanted.match(/^var\((--[\w-]+)\)$/);
   const wantedValue = asVar ? (tokens.get(asVar[1]) ?? wanted) : wanted;

   for (const [token, value] of tokens)
      if (value === wantedValue && new RegExp(`${prop}\\s*:\\s*var\\(\\s*${token}\\b`).test(pageCss))
         return `token ${token}`;

   if (INERT.has(wantedValue) && !new RegExp(`(?:^|[;{])\\s*${prop}\\s*:`, "m").test(pageCss))
      return "never set";

   return null;
}

if (process.argv[2] === "--accept") {
   const page = process.argv[3];
   const reason = process.argv[4] ?? "verified by probe --audit-light";
   if (!page || !ported.has(page)) {
      console.error("usage: node theme-audit.mjs --accept <ported-page> [reason]");
      process.exit(1);
   }
   const debt = frozen[page] ?? [];
   const present = lightDeclsInBuild(page) ?? new Set();
   const pageCss = builtCss(page);
   const tokens = lightTokens();
   const list = [];
   for (const rule of debt)
      for (const decl of rule.decls)
         if (!isPaid(decl, present, pageCss, tokens)) list.push(`${rule.targets.join(", ")} -> ${decl}`);
   accepted[page] = { reason, declarations: list };
   writeFileSync(debtFile, JSON.stringify({ debt: frozen, accepted }, null, 3) + "\n");
   console.log(`accepted ${list.length} declaration(s) for ${page}: ${reason}`);
   process.exit(0);
}

const only = process.argv[2];
const targetPages = only ? [only] : allPages;
let missingTotal = 0;

console.log(`theme.css: ${rules.length} component rule(s) that CSS Modules would break.\n`);

for (const page of targetPages) {
   if (ported.has(page)) {
      const debt = frozen[page] ?? deriveDebt(page);
      if (!debt) {
         console.log(`${page}  [ported]  no frozen debt recorded — run: node theme-audit.mjs --freeze`);
         continue;
      }
      if (!debt.length) {
         console.log(`${page}  [ported]  owed nothing.`);
         continue;
      }
      const present = lightDeclsInBuild(page);
      if (present === null) {
         console.log(`${page}  [ported]  not built yet.`);
         continue;
      }
      const pageCss = builtCss(page);
      const tokens = lightTokens();
      const missing = [];
      const how = new Map();
      for (const rule of debt)
         for (const decl of rule.decls) {
            const paid = isPaid(decl, present, pageCss, tokens);
            const line = `${rule.targets.join(", ")} -> ${decl}`;
            if (paid) how.set(paid, (how.get(paid) ?? 0) + 1);
            else if ((accepted[page]?.declarations ?? []).includes(line))
               how.set("accepted (measured)", (how.get("accepted (measured)") ?? 0) + 1);
            else missing.push(line);
         }

      if (!missing.length) {
         const via = [...how].map(([k, n]) => `${n} via ${k}`).join(", ");
         console.log(`${page}  [ported]  PAID — ${debt.length} rule(s) satisfied (${via}).`);
      } else {
         missingTotal += missing.length;
         console.log(`${page}  [ported]  *** ${missing.length} DECLARATION(S) MISSING — light mode is broken:`);
         for (const m of missing) console.log(`      ${m}`);
      }
      continue;
   }

   const debt = deriveDebt(page);
   if (!debt) continue;
   if (!debt.length) {
      console.log(`${page}  [pending] owes nothing — token overrides only. Safe to port.`);
      continue;
   }
   console.log(`${page}  [pending] owes ${debt.length} rule(s):`);
   for (const rule of debt) {
      console.log(`      ${rule.targets.join(", ")}`);
      for (const d of rule.decls) console.log(`         ${d};`);
   }
}

if (missingTotal) {
   console.log(`\n${missingTotal} unpaid declaration(s). A ported page must reproduce its light rules.`);
   process.exit(1);
}
