import type { Category, LaunchOption, PresetName, CvarValues } from "./types";

export const SETTINGS: Record<string, Category> = {
   "DISPLAY & FPS": {
      cvars: {
         fps_max: {
            label: "Max FPS (In-Game)",
            type: "input",
            default: "0",
            tip: "0 = uncapped. Match your monitor refresh rate for stability.",
         },
         fps_max_ui: {
            label: "Dashboard Max FPS",
            type: "input",
            default: "60",
            tip: "Stops the menu from cooking your GPU.",
         },
         mat_viewportscale: {
            label: "Render Quality",
            type: "select",
            options: {
               "1.0": "100%",
               "0.91": "91%",
               "0.85": "85%",
               "0.81": "81%",
               "0.71": "71%",
               "0.60": "60%",
            },
            default: "1.0",
            tip: "Lower = more FPS but softer image. Use with FSR.",
         },
         r_fullscreen_gamma: {
            label: "Gamma",
            type: "input",
            default: "2.2",
            tip: "Default 2.2. Adjust for monitor brightness.",
         },
      },
   },
   "VISUAL TOGGLES": {
      cvars: {
         dota_portrait_animate: {
            label: "Animate Portrait",
            type: "toggle",
            default: "0",
            tip: "Reduces extra UI animation overhead.",
         },
         r_deferred_additive_pass: {
            label: "Additive Light Pass",
            type: "toggle",
            default: "0",
            tip: "Removes extra lighting passes and reflections.",
         },
         r_deferred_simple_light: {
            label: "World Lighting",
            type: "toggle",
            default: "1",
            tip: "Large GPU cost for cosmetic gain. 1=Simple, 0=Off.",
         },
         r_ssao: {
            label: "Ambient Occlusion",
            type: "toggle",
            default: "0",
            tip: "One of the fastest ways to gain FPS.",
         },
         r_dota_normal_maps: {
            label: "Normal Maps",
            type: "toggle",
            default: "1",
            tip: "Reduces surface detail calculations.",
         },
         r_dota_allow_parallax_mapping: {
            label: "Ground Parallax",
            type: "toggle",
            default: "0",
            tip: "Depth effects on terrain, irrelevant in fights.",
         },
         dota_ambient_creatures: {
            label: "Ambient Creatures",
            type: "toggle",
            default: "0",
            tip: "Eliminates extra background units.",
         },
         dota_ambient_cloth: {
            label: "Ambient Cloth Sim",
            type: "toggle",
            default: "1",
            tip: "Prevents cloth physics overhead.",
         },
         r_grass_quality: {
            label: "Grass",
            type: "select",
            options: {
               "0": "Off",
               "2": "Low",
               "3": "Medium",
               "4": "High",
            },
            default: "0",
            tip: "Dense ground detail that costs FPS.",
         },
         r_dota_fxaa: {
            label: "Anti-Aliasing",
            type: "toggle",
            default: "0",
            tip: "AA is a clarity trade. Off improves sharpness.",
         },
         r_deferred_specular: {
            label: "Specular",
            type: "toggle",
            default: "0",
            tip: "Reduces shiny highlights and lighting work.",
         },
         r_deferred_specular_bloom: {
            label: "Specular & Light Blooms",
            type: "toggle",
            default: "0",
            tip: "Bloom washes out spell effects.",
         },
         dota_cheap_water: {
            label: "Cheap Water",
            type: "toggle",
            default: "1",
            tip: "1=cheap water for better FPS near river.",
         },
         r_deferred_height_fog: {
            label: "Atmospheric Fog",
            type: "toggle",
            default: "0",
            tip: "Removes atmospheric effects that spike in fights.",
         },
         r_dashboard_render_quality: {
            label: "HQ Dashboard",
            type: "toggle",
            default: "0",
            tip: "Reduces menu GPU load.",
         },
         r_dota_allow_wind_on_trees: {
            label: "Tree Wind",
            type: "toggle",
            default: "0",
            tip: "Removes constant environmental animation.",
         },
         r_dota_bloom_compute_shader: {
            label: "Compute Shaders",
            type: "toggle",
            default: "1",
            tip: "Recommended ON for modern GPUs.",
         },
      },
   },
   QUALITY: {
      cvars: {
         r_texture_stream_mip_bias: {
            label: "Texture Quality",
            type: "select",
            options: {
               "0": "Ultra",
               "1": "High",
               "2": "Medium",
               "3": "Low",
            },
            default: "0",
            tip: "Mostly a VRAM issue. Keep higher for clarity.",
         },
         cl_particle_fallback_base: {
            label: "Effects Quality",
            type: "select",
            options: {
               "0": "Ultra",
               "2": "Medium",
               "4": "Low",
            },
            default: "2",
            tip: "Spell effects spike load. Low = stable.",
         },
         cl_globallight_shadow_mode: {
            label: "Shadow Quality",
            type: "select",
            options: {
               "0": "Off",
               "1": "Low",
               "2": "Medium",
               "3": "High",
            },
            default: "1",
            tip: "Shadows are the most expensive setting.",
         },
         r_texturefilteringquality: {
            label: "Texture Filtering",
            type: "select",
            options: {
               "0": "Bilinear",
               "1": "Trilinear",
               "3": "Aniso 8x",
               "5": "Aniso 16x",
            },
            default: "3",
            tip: "Higher = sharper textures at angles.",
         },
      },
   },
   "ENGINE TWEAKS": {
      cvars: {
         cl_particle_fallback_multiplier: {
            label: "Particle Fallback Multi",
            type: "input",
            default: "4",
            tip: "Higher = more aggressive particle LOD.",
         },
         cl_particle_sim_fallback_threshold_ms: {
            label: "Particle Sim Threshold (ms)",
            type: "input",
            default: "4",
            tip: "Max particle simulation time.",
         },
         dota_allow_clientside_particles: {
            label: "Client-side Particles",
            type: "toggle",
            default: "0",
            tip: "Non-essential cosmetic particles.",
         },
         dota_disable_particle_lights: {
            label: "Disable Particle Lights",
            type: "toggle",
            default: "1",
            tip: "Removes light from particles.",
         },
         lb_shadow_texture_width_override: {
            label: "Shadow Tex Width",
            type: "input",
            default: "128",
            tip: "Lower = less detail, more FPS.",
         },
         lb_shadow_texture_height_override: {
            label: "Shadow Tex Height",
            type: "input",
            default: "128",
            tip: "Lower = less detail, more FPS.",
         },
         r_dota_spotlight_shadows_resolution: {
            label: "Spotlight Shadow Res",
            type: "input",
            default: "128",
            tip: "Spotlight shadows resolution.",
         },
         r_particle_max_detail_level: {
            label: "Particle Max Detail",
            type: "select",
            options: {
               "0": "Low",
               "1": "Medium",
               "2": "High",
               "3": "Ultra",
            },
            default: "0",
            tip: "Particle detail level.",
         },
         r_dota_color_correction: {
            label: "Color Correction",
            type: "toggle",
            default: "0",
            tip: "Extra post-processing.",
         },
         r_dota_render_2d_skybox: {
            label: "Skybox Clouds",
            type: "toggle",
            default: "0",
            tip: "Skybox cloud rendering.",
         },
         engine_no_focus_sleep: {
            label: "Alt-Tab Sleep (ms)",
            type: "input",
            default: "20",
            tip: "Power savings while alt-tabbed.",
         },
      },
   },
   "VSYNC & LATENCY": {
      cvars: {
         engine_low_latency_sleep_after_client_tick: {
            label: "Low Latency Sleep",
            type: "toggle",
            default: "1",
            tip: "VSync OFF with less tearing.",
         },
         r_experimental_lag_limiter: {
            label: "Experimental Lag Limiter",
            type: "toggle",
            default: "1",
            tip: "VSync ON with less input lag.",
         },
         r_low_latency: {
            label: "NVIDIA Reflex",
            type: "select",
            options: {
               "0": "Off",
               "1": "On",
               "2": "On + Boost",
            },
            default: "2",
            tip: "Reduces system latency on NVIDIA GPUs.",
         },
      },
   },
   NETWORK: {
      cvars: {
         rate: {
            label: "Net Rate",
            type: "input",
            default: "80000",
            tip: "Max receive rate.",
         },
         cl_updaterate: {
            label: "Update Rate",
            type: "input",
            default: "60",
            tip: "Net updates per second.",
         },
         cl_interp_ratio: {
            label: "Interp Ratio",
            type: "input",
            default: "2",
            tip: "Interpolation ratio.",
         },
         cl_smooth: {
            label: "Smooth Interp",
            type: "toggle",
            default: "1",
            tip: "Smooth interpolation errors.",
         },
      },
   },
};

export const LAUNCH_OPTIONS: LaunchOption[] = [
   {
      flag: "-novid",
      desc: "Skips the intro video on startup.",
      default: true,
   },
   {
      flag: "-console",
      desc: "Enables the developer console.",
      default: true,
   },
   {
      flag: "-fullscreen",
      desc: "Forces exclusive fullscreen mode.",
      default: false,
   },
   {
      flag: "-force_allow_excl_fullscreen",
      desc: "Allows exclusive fullscreen with compositing.",
      default: false,
   },
   {
      flag: "-coop_fullscreen",
      desc: "Desktop-friendly fullscreen mode.",
      default: false,
   },
   {
      flag: "-force_allow_coop_fullscreen",
      desc: "Forces cooperative fullscreen support.",
      default: false,
   },
   {
      flag: "-favor_consistent_framerate",
      desc: "Prioritizes consistent frame times.",
      default: true,
   },
   {
      flag: "-skip_download_player_info",
      desc: "Skips downloading player info on load.",
      default: true,
   },
   {
      flag: "-high",
      desc: "Sets process to high priority.",
      default: false,
   },
   {
      flag: "-r_max_device_threads 32",
      desc: "Max rendering threads.",
      default: false,
   },
   {
      flag: "-threads 9",
      desc: "CPU threads for the engine.",
      default: false,
   },
   {
      flag: "-mainthreadpriority 2",
      desc: "Main thread scheduling priority.",
      default: false,
   },
   {
      flag: "-set_power_qos_disable",
      desc: "Disables Windows power throttling.",
      default: false,
   },
   {
      flag: "-map_enable_background_maps 0",
      desc: "Disables animated menu backgrounds.",
      default: false,
   },
   {
      flag: "-prewarm_panorama",
      desc: "Pre-warms UI to reduce first-load stutters.",
      default: false,
   },
   {
      flag: "-noaafonts",
      desc: "Disables font anti-aliasing.",
      default: false,
   },
];

export const PRESETS: Record<PresetName, CvarValues> = {
   potato: {
      fps_max: "57",
      fps_max_ui: "20",
      mat_viewportscale: "0.71",
      r_fullscreen_gamma: "2.2",
      dota_portrait_animate: "0",
      r_deferred_additive_pass: "0",
      r_deferred_simple_light: "0",
      r_ssao: "0",
      r_dota_normal_maps: "0",
      r_dota_allow_parallax_mapping: "0",
      dota_ambient_creatures: "0",
      dota_ambient_cloth: "0",
      r_grass_quality: "0",
      r_dota_fxaa: "0",
      r_deferred_specular: "0",
      r_deferred_specular_bloom: "0",
      dota_cheap_water: "1",
      r_deferred_height_fog: "0",
      r_dashboard_render_quality: "0",
      r_dota_allow_wind_on_trees: "0",
      r_dota_bloom_compute_shader: "0",
      r_texture_stream_mip_bias: "3",
      cl_particle_fallback_base: "4",
      cl_globallight_shadow_mode: "0",
      r_texturefilteringquality: "0",
      cl_particle_fallback_multiplier: "4",
      cl_particle_sim_fallback_threshold_ms: "4",
      dota_allow_clientside_particles: "0",
      dota_disable_particle_lights: "1",
      lb_shadow_texture_width_override: "128",
      lb_shadow_texture_height_override: "128",
      r_dota_spotlight_shadows_resolution: "128",
      r_particle_max_detail_level: "0",
      r_dota_color_correction: "0",
      r_dota_render_2d_skybox: "0",
      engine_no_focus_sleep: "20",
      engine_low_latency_sleep_after_client_tick: "0",
      r_experimental_lag_limiter: "0",
      r_low_latency: "0",
      rate: "80000",
      cl_updaterate: "60",
      cl_interp_ratio: "2",
      cl_smooth: "1",
   },
   low: {
      fps_max: "90",
      fps_max_ui: "30",
      mat_viewportscale: "0.81",
      r_fullscreen_gamma: "2.2",
      dota_portrait_animate: "0",
      r_deferred_additive_pass: "0",
      r_deferred_simple_light: "1",
      r_ssao: "0",
      r_dota_normal_maps: "0",
      r_dota_allow_parallax_mapping: "0",
      dota_ambient_creatures: "0",
      dota_ambient_cloth: "1",
      r_grass_quality: "0",
      r_dota_fxaa: "0",
      r_deferred_specular: "0",
      r_deferred_specular_bloom: "0",
      dota_cheap_water: "1",
      r_deferred_height_fog: "0",
      r_dashboard_render_quality: "0",
      r_dota_allow_wind_on_trees: "0",
      r_dota_bloom_compute_shader: "0",
      r_texture_stream_mip_bias: "2",
      cl_particle_fallback_base: "4",
      cl_globallight_shadow_mode: "0",
      r_texturefilteringquality: "0",
      cl_particle_fallback_multiplier: "4",
      cl_particle_sim_fallback_threshold_ms: "4",
      dota_allow_clientside_particles: "0",
      dota_disable_particle_lights: "1",
      lb_shadow_texture_width_override: "128",
      lb_shadow_texture_height_override: "128",
      r_dota_spotlight_shadows_resolution: "128",
      r_particle_max_detail_level: "0",
      r_dota_color_correction: "0",
      r_dota_render_2d_skybox: "0",
      engine_no_focus_sleep: "20",
      engine_low_latency_sleep_after_client_tick: "1",
      r_experimental_lag_limiter: "0",
      r_low_latency: "1",
      rate: "80000",
      cl_updaterate: "60",
      cl_interp_ratio: "2",
      cl_smooth: "1",
   },
   medium: {
      fps_max: "120",
      fps_max_ui: "60",
      mat_viewportscale: "0.91",
      r_fullscreen_gamma: "2.2",
      dota_portrait_animate: "1",
      r_deferred_additive_pass: "1",
      r_deferred_simple_light: "1",
      r_ssao: "0",
      r_dota_normal_maps: "1",
      r_dota_allow_parallax_mapping: "0",
      dota_ambient_creatures: "0",
      dota_ambient_cloth: "1",
      r_grass_quality: "2",
      r_dota_fxaa: "0",
      r_deferred_specular: "1",
      r_deferred_specular_bloom: "0",
      dota_cheap_water: "1",
      r_deferred_height_fog: "1",
      r_dashboard_render_quality: "0",
      r_dota_allow_wind_on_trees: "1",
      r_dota_bloom_compute_shader: "1",
      r_texture_stream_mip_bias: "1",
      cl_particle_fallback_base: "2",
      cl_globallight_shadow_mode: "1",
      r_texturefilteringquality: "1",
      cl_particle_fallback_multiplier: "4",
      cl_particle_sim_fallback_threshold_ms: "4",
      dota_allow_clientside_particles: "0",
      dota_disable_particle_lights: "1",
      lb_shadow_texture_width_override: "128",
      lb_shadow_texture_height_override: "128",
      r_dota_spotlight_shadows_resolution: "128",
      r_particle_max_detail_level: "1",
      r_dota_color_correction: "0",
      r_dota_render_2d_skybox: "0",
      engine_no_focus_sleep: "20",
      engine_low_latency_sleep_after_client_tick: "1",
      r_experimental_lag_limiter: "0",
      r_low_latency: "2",
      rate: "80000",
      cl_updaterate: "60",
      cl_interp_ratio: "2",
      cl_smooth: "1",
   },
   high: {
      fps_max: "240",
      fps_max_ui: "120",
      mat_viewportscale: "1.0",
      r_fullscreen_gamma: "2.2",
      dota_portrait_animate: "1",
      r_deferred_additive_pass: "1",
      r_deferred_simple_light: "1",
      r_ssao: "0",
      r_dota_normal_maps: "1",
      r_dota_allow_parallax_mapping: "1",
      dota_ambient_creatures: "1",
      dota_ambient_cloth: "1",
      r_grass_quality: "3",
      r_dota_fxaa: "1",
      r_deferred_specular: "1",
      r_deferred_specular_bloom: "1",
      dota_cheap_water: "0",
      r_deferred_height_fog: "1",
      r_dashboard_render_quality: "1",
      r_dota_allow_wind_on_trees: "1",
      r_dota_bloom_compute_shader: "1",
      r_texture_stream_mip_bias: "0",
      cl_particle_fallback_base: "0",
      cl_globallight_shadow_mode: "2",
      r_texturefilteringquality: "3",
      cl_particle_fallback_multiplier: "2",
      cl_particle_sim_fallback_threshold_ms: "6",
      dota_allow_clientside_particles: "1",
      dota_disable_particle_lights: "0",
      lb_shadow_texture_width_override: "-1",
      lb_shadow_texture_height_override: "-1",
      r_dota_spotlight_shadows_resolution: "256",
      r_particle_max_detail_level: "2",
      r_dota_color_correction: "1",
      r_dota_render_2d_skybox: "1",
      engine_no_focus_sleep: "20",
      engine_low_latency_sleep_after_client_tick: "1",
      r_experimental_lag_limiter: "0",
      r_low_latency: "2",
      rate: "80000",
      cl_updaterate: "60",
      cl_interp_ratio: "2",
      cl_smooth: "1",
   },
   ultra: {
      fps_max: "0",
      fps_max_ui: "120",
      mat_viewportscale: "1.0",
      r_fullscreen_gamma: "2.2",
      dota_portrait_animate: "1",
      r_deferred_additive_pass: "1",
      r_deferred_simple_light: "1",
      r_ssao: "1",
      r_dota_normal_maps: "1",
      r_dota_allow_parallax_mapping: "1",
      dota_ambient_creatures: "1",
      dota_ambient_cloth: "1",
      r_grass_quality: "4",
      r_dota_fxaa: "1",
      r_deferred_specular: "1",
      r_deferred_specular_bloom: "1",
      dota_cheap_water: "0",
      r_deferred_height_fog: "1",
      r_dashboard_render_quality: "1",
      r_dota_allow_wind_on_trees: "1",
      r_dota_bloom_compute_shader: "1",
      r_texture_stream_mip_bias: "0",
      cl_particle_fallback_base: "0",
      cl_globallight_shadow_mode: "3",
      r_texturefilteringquality: "5",
      cl_particle_fallback_multiplier: "2",
      cl_particle_sim_fallback_threshold_ms: "6",
      dota_allow_clientside_particles: "1",
      dota_disable_particle_lights: "0",
      lb_shadow_texture_width_override: "-1",
      lb_shadow_texture_height_override: "-1",
      r_dota_spotlight_shadows_resolution: "256",
      r_particle_max_detail_level: "3",
      r_dota_color_correction: "1",
      r_dota_render_2d_skybox: "1",
      engine_no_focus_sleep: "20",
      engine_low_latency_sleep_after_client_tick: "1",
      r_experimental_lag_limiter: "0",
      r_low_latency: "2",
      rate: "1000000",
      cl_updaterate: "60",
      cl_interp_ratio: "2",
      cl_smooth: "1",
   },
   competitive: {
      fps_max: "0",
      fps_max_ui: "60",
      mat_viewportscale: "0.81",
      r_fullscreen_gamma: "2.2",
      dota_portrait_animate: "0",
      r_deferred_additive_pass: "0",
      r_deferred_simple_light: "1",
      r_ssao: "0",
      r_dota_normal_maps: "1",
      r_dota_allow_parallax_mapping: "0",
      dota_ambient_creatures: "0",
      dota_ambient_cloth: "1",
      r_grass_quality: "0",
      r_dota_fxaa: "0",
      r_deferred_specular: "0",
      r_deferred_specular_bloom: "0",
      dota_cheap_water: "1",
      r_deferred_height_fog: "0",
      r_dashboard_render_quality: "0",
      r_dota_allow_wind_on_trees: "0",
      r_dota_bloom_compute_shader: "1",
      r_texture_stream_mip_bias: "0",
      cl_particle_fallback_base: "2",
      cl_globallight_shadow_mode: "1",
      r_texturefilteringquality: "3",
      cl_particle_fallback_multiplier: "4",
      cl_particle_sim_fallback_threshold_ms: "4",
      dota_allow_clientside_particles: "0",
      dota_disable_particle_lights: "1",
      lb_shadow_texture_width_override: "128",
      lb_shadow_texture_height_override: "128",
      r_dota_spotlight_shadows_resolution: "128",
      r_particle_max_detail_level: "0",
      r_dota_color_correction: "0",
      r_dota_render_2d_skybox: "0",
      engine_no_focus_sleep: "20",
      engine_low_latency_sleep_after_client_tick: "1",
      r_experimental_lag_limiter: "1",
      r_low_latency: "2",
      rate: "80000",
      cl_updaterate: "60",
      cl_interp_ratio: "2",
      cl_smooth: "1",
   },
};
